<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>ModrixIcon.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<AssemblyTitle>Modrix Installer</AssemblyTitle>
	<AssemblyDescription>The Installer for Modrix</AssemblyDescription>
	<AssemblyCompany>Modrix</AssemblyCompany>
	<AssemblyProduct>Modrix Installer</AssemblyProduct>
	<AssemblyCopyright>Copyright © Modrix 2025</AssemblyCopyright>
	<AssemblyVersion>1.0.0.0</AssemblyVersion>
	<FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

	<!-- Publishing-specific properties -->
	<PropertyGroup Condition="'$(PublishSingleFile)' == 'true'">
		<SelfContained>true</SelfContained>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<PublishReadyToRun>true</PublishReadyToRun>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Net.Http.Json" Version="9.0.9" />
    <PackageReference Include="WPF-UI" Version="4.0.2" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0 " />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\wpfui-icon-256.png" />
    <None Remove="Assets\wpfui-icon-1024.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\wpfui-icon-256.png" />
    <Resource Include="Assets\wpfui-icon-1024.png" />
    <Resource Include="Icons\ConsoleIcon.png" />
    <Resource Include="Icons\DisIcon.png" />
    <Resource Include="Icons\DonateIcon.png" />
    <Resource Include="Icons\FeedbackIcon.png" />
    <Resource Include="Icons\HomeIcon.png" />
    <Resource Include="Icons\ItemIcon.png" />
    <Resource Include="Icons\LanguageControlIcon.png" />
    <Resource Include="Icons\ModrixGitHub.png" />
    <Resource Include="Icons\NewsIcon.png" />
    <Resource Include="Icons\NoWifiIcon.png" />
    <Resource Include="Icons\SettingsIcon.png" />
    <Resource Include="Icons\SourceCodeIcon.png" />
    <Resource Include="Icons\WarningIcon.png" />
    <Resource Include="Icons\WorkspaceIcon.png" />
    <Resource Include="ModrixIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModrixIcon.ico" />
    <Content Include="LICENSE">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
